Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/CourseController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class CourseController : Controller
	{
		private readonly CourseService _courseService;

		public CourseController(CourseService courseService)
		{
			_courseService = courseService;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.GetCourseByCoordIdTaskAsync(token);

			return response.StatusCode switch
			{
				HttpStatusCode.OK => View("/Views/Coordinator/Course/Index.cshtml", response),
				HttpStatusCode.NotFound => View("/Views/Coordinator/Course/CourseNotFound.cshtml", response.Object),
				_ => View("/Views/Coordinator/Course/AddCourse.cshtml", response),
			};
		}

		[HttpGet("Add")]
		public async Task<IActionResult> AddCourse()
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.GetCourseByCoordIdTaskAsync(token);

			return View("/Views/Coordinator/Course/AddCourse.cshtml", response);
		}

		[HttpPost("Add")]
		public async Task<IActionResult> AddCourse(ResultModel<CourseVO> newCourse)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.AddCourseTaskAsync(newCourse.Object, token);

			return response.StatusCode switch
			{
				HttpStatusCode.Created => View("/Views/Coordinator/Course/Index.cshtml", response),
				_ => View("/Views/Coordinator/Course/AddCourse.cshtml", response),
			};
		}

		[HttpGet("Update")]
		public async Task<IActionResult> UpdateCourse()
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.GetCourseByCoordIdTaskAsync(token);

			return View("/Views/Coordinator/Course/UpdateCourse.cshtml", response);
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateCourse(ResultModel<CourseVO> request)
		{
			string token = User.FindFirst("Token").Value;
			request.Object.CoordinatorId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<CourseVO> response = await _courseService.UpdateCourseTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Course/UpdateCourse.cshtml", new ResultModel<CourseVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<CourseVO> courseResponse = await _courseService.GetCourseByCoordIdTaskAsync(token);

			if (courseResponse.StatusCode == HttpStatusCode.OK)
			{
				courseResponse.Message = response.Message;
				courseResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Course/Index.cshtml", courseResponse);
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/DisciplinesController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class DisciplinesController : Controller
	{
		[HttpGet]
		public async Task<IActionResult> Index([FromServices] DisciplineService disciplineService)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<List<DisciplineVO>> response = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

			return View("/Views/Coordinator/Disciplines/Index.cshtml", response);
		}

		[HttpGet("Add")]
		public IActionResult Add() => View("/Views/Coordinator/Disciplines/Add.cshtml");

		[HttpPost]
		public async Task<IActionResult> AddDiscipline([FromServices] DisciplineService disciplineService, ResultModel<DisciplineVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<DisciplineVO> response = await disciplineService.AddDisciplineTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Disciplines/Add.cshtml", new ResultModel<DisciplineVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplinesResponse = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

			if (disciplinesResponse.StatusCode == HttpStatusCode.OK)
			{
				disciplinesResponse.Message = response.Message;
				disciplinesResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Disciplines/Index.cshtml", disciplinesResponse);
		}

		[HttpGet("Update/{disciplineId}")]
		public async Task<IActionResult> Update([FromServices] DisciplineService disciplineService, [Required] Guid disciplineId)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<DisciplineVO> response = await disciplineService.GetDisciplineByDisciplineIdTaskAsync(disciplineId, token);

			return View("/Views/Coordinator/Disciplines/Update.cshtml", response);
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateDiscipline([FromServices] DisciplineService disciplineService, ResultModel<DisciplineVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<DisciplineVO> response = await disciplineService.UpdateDisciplineTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Disciplines/Update.cshtml", new ResultModel<DisciplineVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplinesResponse = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

			if (disciplinesResponse.StatusCode == HttpStatusCode.OK)
			{
				disciplinesResponse.Message = response.Message;
				disciplinesResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Disciplines/Index.cshtml", disciplinesResponse);
		}

		[HttpPost("Delete/{disciplineId}")]
		public async Task<IActionResult> Delete([FromServices] DisciplineService disciplineService, [Required] Guid disciplineId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<bool> response = await disciplineService.DeleteDisciplineTaskAsync(disciplineId, token);

				ResultModel<List<DisciplineVO>> disciplinesResponse = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

				if (disciplinesResponse.StatusCode == HttpStatusCode.OK)
				{
					disciplinesResponse.StatusCode = response.StatusCode;
					disciplinesResponse.Message = response.Message;
				}

				return View("/Views/Coordinator/Disciplines/Index.cshtml", disciplinesResponse);
			}

			return BadRequest();
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/LessonsController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO;
using UniLinks.Dependencies.Data.VO.Lesson;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class LessonsController : Controller
	{
		[HttpGet]
		public async Task<IActionResult> Index([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
			ResultModel<List<LessonDisciplineVO>> lessons = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

			return View("/Views/Coordinator/Lessons/Index.cshtml", lessons);
		}

		[HttpGet("Add")]
		public IActionResult Add() => View("/Views/Coordinator/Lessons/Add.cshtml");

		[HttpPost]
		public async Task<IActionResult> AddLesson([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService, ResultModel<LessonVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<LessonVO> response = await lessonService.AddLessonTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Lessons/Add.cshtml", new ResultModel<LessonVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
			ResultModel<List<LessonDisciplineVO>> lessonsResponse = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

			if (lessonsResponse.StatusCode == HttpStatusCode.OK)
			{
				lessonsResponse.Message = response.Message;
				lessonsResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Lessons/Index.cshtml", lessonsResponse);
		}

		[HttpGet("Update/{lessonId}")]
		public async Task<IActionResult> Update([FromServices] LessonService lessonService, [Required] Guid lessonId)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<LessonVO> response = await lessonService.GetLessonByIdTaskAsync(lessonId, token);

			return View("/Views/Coordinator/Lessons/Update.cshtml", response);
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateLesson([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService, ResultModel<LessonVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<LessonVO> response = await lessonService.UpdateLessonTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Lessons/Update.cshtml", new ResultModel<LessonVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
			ResultModel<List<LessonDisciplineVO>> lessonsResponse = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

			if (lessonsResponse.StatusCode == HttpStatusCode.OK)
			{
				lessonsResponse.Message = response.Message;
				lessonsResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Lessons/Index.cshtml", lessonsResponse);
		}

		[HttpPost("Delete/{lessonId}")]
		public async Task<IActionResult> Delete([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService, [Required] Guid lessonId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<bool> response = await lessonService.RemoveLessonTaskAsync(lessonId, token);

				ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
				ResultModel<List<LessonDisciplineVO>> lessons = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

				if (disciplines.StatusCode == HttpStatusCode.OK && lessons.StatusCode == HttpStatusCode.OK)
				{
					lessons.StatusCode = response.StatusCode;
					lessons.Message = response.Message;
				}

				return View("/Views/Coordinator/Lessons/Index.cshtml", lessons);
			}

			return BadRequest();
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/StudentsController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO.Student;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class StudentsController : Controller
	{
		[HttpGet]
		public async Task<IActionResult> Index([FromServices] StudentsService studentsService)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<List<StudentDisciplineVO>> students = await studentsService.GetStudentsTaskAsync(token);
			return View("/Views/Coordinator/Students/Index.cshtml", students);
		}

		[HttpGet("Add")]
		public IActionResult Add() => View("/Views/Coordinator/Students/Add.cshtml");

		[HttpPost("Add")]
		public async Task<IActionResult> AddStudent([FromServices] StudentsService studentsService, ResultModel<StudentDisciplineVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.Student.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<StudentDisciplineVO> response = await studentsService.AddStudentTaskAsync(request.Object.Student, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Students/Add.cshtml", new ResultModel<StudentDisciplineVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<StudentDisciplineVO>> studentResponse = await studentsService.GetStudentsTaskAsync(token);

			if (studentResponse.StatusCode == HttpStatusCode.OK)
			{
				studentResponse.Message = response.Message;
				studentResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Students/Index.cshtml", studentResponse);
		}

		[HttpGet("Update/{studentId}")]
		public async Task<IActionResult> Update([FromServices] StudentsService studentsService, [Required] Guid studentId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<StudentDisciplineVO> response = await studentsService.GetStudentTaskAsync(token, studentId);

				return View("/Views/Coordinator/Students/Update.cshtml", response);
			}

			return BadRequest();
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateStudent([FromServices] StudentsService studentsService, ResultModel<StudentDisciplineVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.Student.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<StudentDisciplineVO> response = await studentsService.UpdateStudentTaskAsync(request.Object.Student, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Students/Update.cshtml", new ResultModel<StudentDisciplineVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<StudentDisciplineVO>> studentResponse = await studentsService.GetStudentsTaskAsync(token);

			if (studentResponse.StatusCode == HttpStatusCode.OK)
			{
				studentResponse.Message = response.Message;
				studentResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Students/Index.cshtml", studentResponse);
		}

		[HttpPost("Delete/{studentId}")]
		public async Task<IActionResult> Delete([FromServices] StudentsService studentsService, [Required] Guid studentId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<bool> response = await studentsService.RemoveStudentTaskAsync(studentId, token);
				ResultModel<List<StudentDisciplineVO>> studentResponse = await studentsService.GetStudentsTaskAsync(token);

				studentResponse.Message = response.Message;
				studentResponse.StatusCode = response.StatusCode;

				return View("/Views/Coordinator/Students/Index.cshtml", studentResponse);
			}

			return NotFound();
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Views/Shared/EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniLinks</title>
    <base href="~/" />
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/mdb.min.css" rel="stylesheet" />
    <link href="css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link id="clientThemeLink" href="css/theme.light.css" rel="stylesheet" />
</head>
<body id="home" class="theme-bg theme-text">
    <noscript>Habilite o javascript para o site funcionar!</noscript>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/Notifier.js"></script>

    <main class="main">
        @RenderBody()
    </main>

    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/mdb.min.js"></script>
    <script src="~/js/site.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>

Speckoz.UniLinks/UniLinks.Client.Site/Views/Shared/ErrorsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniBugs</title>
    <base href="~/" />
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/mdb.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link id="clientThemeLink" href="css/theme.dark.css" rel="stylesheet" />
</head>
<body id="home" class="theme-bg theme-text">
    <main class="main">
        @RenderBody()
    </main>

    @RenderSection("Scripts", false)
</body>
</html>

Speckoz.UniLinks/UniLinks.Client.Site/Views/Shared/Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http

@inject UniLinks.Client.Site.Services.Coordinator.CourseService _courseService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniLinks</title>
    <base href="~/" />
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/mdb.min.css" rel="stylesheet" />
    <link href="css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="css/datatables.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/choices.css" />
    <link id="clientThemeLink" href="css/theme.light.css" rel="stylesheet" />
</head>
<body id="home" class="theme-bg theme-text" onload="checkTheme()">
    <noscript>Habilite o javascript para o site funcionar!</noscript>
    <div class="app">
        <aside class="sidebar" style="display: table">
            <div class="navbar shadow-sm main-navbar-aside">
                <a class="navbar-brand font-nav-title animated heartBeat delay-3s slower" href="/">
                    <span style="color: white;">Uni</span><span style="color: darkorange;">Links</span>
                </a>
                <button data-toggle="collapse" data-target="#navbarResponsive-panel" class="navbar-toggler navbar-toggler-right" type="button"
                        aria-controls="navbarResponsive-panel" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="mdi mdi-menu mdi-36px text-white"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive-panel">
                    <div style="margin: 10px; color: #d2d2d2; font-size: 15px">
                        <p style="margin: 0">Conectado como</p>
                        <p style="margin: 0; margin-bottom: -4px">@User.FindFirst(ClaimTypes.Name).Value</p>
                        @if (User.FindFirst(ClaimTypes.Role)?.Value == nameof(UserTypeEnum.Student))
                        {
                            <p style="font-size:13px; font-weight: 700; margin: 0">Aluno</p>
                        }
                        else if (User.FindFirst(ClaimTypes.Role)?.Value == nameof(UserTypeEnum.Coordinator))
                        {
                            <p style="font-size:13px; font-weight: 700; margin: 0">Coordenador</p>
                        }
                    </div>
                    <ul class="nav flex-column animated bounceIn">
                        <li class="nav-item py-0">
                            <a class="nav-link waves-effect" href="">
                                <span class="mdi mdi-home mdi-18px icon-margin-right"></span> Página Inicial
                            </a>
                        </li>
                        @if (User.FindFirst(ClaimTypes.Role)?.Value == nameof(UserTypeEnum.Student))
                        {
                            <li class="nav-item py-0">
                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Student">
                                    <i class="mdi mdi-record-rec mdi-18px icon-margin-right" aria-hidden="true"></i> Minhas Aulas
                                </a>
                            </li>
                            <li class="nav-item py-0">
                                <a class="nav-link waves-effect" asp-action="Classes" asp-controller="Student">
                                    <i class="mdi mdi-google-lesson mdi-18px icon-margin-right" aria-hidden="true"></i> Salas Online
                                </a>
                            </li>
                        }
                        else if (User.FindFirst(ClaimTypes.Role)?.Value == nameof(UserTypeEnum.Coordinator))
                        {
                            <li class="nav-item py-0">
                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Coordinator">
                                    <i class="mdi mdi-account-star mdi-18px icon-margin-right" aria-hidden="true"></i> Painel
                                </a>

                                @{
                                    var request = await _courseService.GetCourseByCoordIdTaskAsync(User.FindFirst("Token").Value);

                                    if (request.StatusCode == System.Net.HttpStatusCode.OK)
                                    {
                                        <ul class="nav flex-column">
                                            <li class="nav-item py-0 nav-panel-margin">
                                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Students">
                                                    <i class="mdi mdi-account-multiple mdi-18px icon-margin-right" aria-hidden="true"></i> Estudantes
                                                </a>
                                            </li>
                                            <li class="nav-item py-0 nav-panel-margin">
                                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Lessons">
                                                    <i class="mdi mdi-record-rec mdi-18px icon-margin-right" aria-hidden="true"></i> Aulas Gravadas
                                                </a>
                                            </li>
                                            <li class="nav-item py-0 nav-panel-margin">
                                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Disciplines">
                                                    <i class="mdi mdi-bookshelf mdi-18px icon-margin-right" aria-hidden="true"></i> Disciplinas
                                                </a>
                                            </li>
                                            <li class="nav-item py-0 nav-panel-margin">
                                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Classes">
                                                    <i class="mdi mdi-google-lesson mdi-18px icon-margin-right" aria-hidden="true"></i> Salas Online
                                                </a>
                                            </li>
                                        </ul>
                                    }
                                }
                            </li>
                            <li class="nav-item py-0">
                                <a class="nav-link waves-effect" asp-action="Index" asp-controller="Course">
                                    <i class="mdi mdi-information-variant mdi-18px icon-margin-right" aria-hidden="true"></i> Informaçao do Curso
                                </a>
                            </li>
                        }
                        <li class="nav-item py-0">
                            <a class="nav-link waves-effect" asp-action="Logout" asp-controller="Home">
                                <i class="mdi mdi-logout mdi-18px icon-margin-right" aria-hidden="true"></i> Deslogar
                            </a>
                        </li>

                        <li class="nav-item py-0">
                            <hr class="separator" />
                        </li>
                        <li class="nav-item py-0">
                            <div class="nav-link waves-effect">
                                <div class="row no-gutters">
                                    <div class="col-auto py-0" style="color: #d7d7d7">
                                        <i class="mdi mdi-theme-light-dark mdi-18px icon-margin-right" style="vertical-align: middle"></i>
                                        <span>Modo Escuro: </span>
                                    </div>
                                    <div class="col-auto align-content-end">
                                        <label class="switch">
                                            <input id="themeCheckbox" type="checkbox" onclick="ChangeTheme()">
                                            <span class="slider round">
                                                <i class="mdi mdi-weather-night mdi-18px icon-margin-right white-text" style="margin-left: 5px;"></i>
                                            </span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li class="nav-item py-0">
                            <a class="nav-link waves-effect" href="/#devs">
                                <i class="mdi mdi-xml mdi-18px icon-margin-right" aria-hidden="true"></i> Desenvolvedores
                            </a>
                        </li>

                        <li class="nav-item py-0">
                            <a class="nav-link waves-effect" href="/#about">
                                <i class="mdi mdi-information-variant mdi-18px icon-margin-right" aria-hidden="true"></i> Sobre
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </aside>

        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/Notifier.js"></script>

        <main role="main" class="main" style="margin: 5px">
            <h5 class="text-center theme-text" style="font-weight: 500; margin: 10px">@ViewData["Title"]</h5>
            <hr />

            @RenderBody()
        </main>

        <script src="~/js/popper.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/mdb.min.js"></script>
        <script src="~/js/datatables.min.js"></script>
        <script src="~/js/site.js"></script>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>