Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/ClassesController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO.Class;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class ClassesController : Controller
	{
		[HttpGet]
		public async Task<IActionResult> Index([FromServices] ClassService classService)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<List<ClassVO>> response = await classService.GetClassesTaskAsync(token);

			return View("/Views/Coordinator/Classes/Index.cshtml", response);
		}

		[HttpGet("Add")]
		public async Task<IActionResult> Add([FromServices] CourseService courseService)
		{
			string token = User.FindFirst("Token").Value;

			ViewBag.periods = (await courseService.GetCourseByCoordIdTaskAsync(token)).Object.Periods;

			return View("/Views/Coordinator/Classes/Add.cshtml");
		}

		[HttpPost("Add")]
		public async Task<IActionResult> AddClass([FromServices] ClassService classService, ResultModel<ClassVO> request)
		{
			string token = User.FindFirst("Token").Value;
			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);
			ResultModel<ClassVO> response = await classService.AddClasseTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Classes/Add.cshtml", new ResultModel<ClassVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<ClassVO>> classResponse = await classService.GetClassesTaskAsync(token);

			if (classResponse.StatusCode == HttpStatusCode.OK)
			{
				classResponse.Message = response.Message;
				classResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Classes/Index.cshtml", classResponse);
		}

		[HttpGet("Update/{classId}")]
		public async Task<IActionResult> Update([FromServices] ClassService classService, [FromServices] CourseService courseService, [Required] Guid classId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<ClassVO> response = await classService.GetClassTaskAsync(classId, token);

				return View("/Views/Coordinator/Classes/Update.cshtml", response);
			}

			return BadRequest();
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateClass([FromServices] ClassService classService, ResultModel<ClassVO> request)
		{
			string token = User.FindFirst("Token").Value;
			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<ClassVO> response = await classService.UpdateClassTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/classes/Update.cshtml", new ResultModel<ClassVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<ClassVO>> classResponse = await classService.GetClassesTaskAsync(token);

			if (classResponse.StatusCode == HttpStatusCode.OK)
			{
				classResponse.Message = response.Message;
				classResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Classes/Index.cshtml", classResponse);
		}

		[HttpPost("Delete/{classId}")]
		public async Task<IActionResult> Delete([FromServices] ClassService classService, [Required] Guid classId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<bool> response = await classService.RemoveClassTaskAsync(classId, token);
				ResultModel<List<ClassVO>> studentResponse = await classService.GetClassesTaskAsync(token);

				studentResponse.Message = response.Message;
				studentResponse.StatusCode = response.StatusCode;

				return View("/Views/Coordinator/Classes/Index.cshtml", studentResponse);
			}

			return NotFound();
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/CourseController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class CourseController : Controller
	{
		private readonly CourseService _courseService;

		public CourseController(CourseService courseService)
		{
			_courseService = courseService;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.GetCourseByCoordIdTaskAsync(token);

			return response.StatusCode switch
			{
				HttpStatusCode.OK => View("/Views/Coordinator/Course/Index.cshtml", response),
				HttpStatusCode.NotFound => View("/Views/Coordinator/Course/CourseNotFound.cshtml", response.Object),
				_ => View("/Views/Coordinator/Course/AddCourse.cshtml", response),
			};
		}

		[HttpGet("Add")]
		public async Task<IActionResult> AddCourse()
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.GetCourseByCoordIdTaskAsync(token);

			return View("/Views/Coordinator/Course/AddCourse.cshtml", response);
		}

		[HttpPost("Add")]
		public async Task<IActionResult> AddCourse(ResultModel<CourseVO> newCourse)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.AddCourseTaskAsync(newCourse.Object, token);

			return response.StatusCode switch
			{
				HttpStatusCode.Created => View("/Views/Coordinator/Course/Index.cshtml", response),
				_ => View("/Views/Coordinator/Course/AddCourse.cshtml", response),
			};
		}

		[HttpGet("Update")]
		public async Task<IActionResult> UpdateCourse()
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<CourseVO> response = await _courseService.GetCourseByCoordIdTaskAsync(token);

			return View("/Views/Coordinator/Course/UpdateCourse.cshtml", response);
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateCourse(ResultModel<CourseVO> request)
		{
			string token = User.FindFirst("Token").Value;
			request.Object.CoordinatorId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<CourseVO> response = await _courseService.UpdateCourseTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Course/UpdateCourse.cshtml", new ResultModel<CourseVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<CourseVO> courseResponse = await _courseService.GetCourseByCoordIdTaskAsync(token);

			if (courseResponse.StatusCode == HttpStatusCode.OK)
			{
				courseResponse.Message = response.Message;
				courseResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Course/Index.cshtml", courseResponse);
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/DisciplinesController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class DisciplinesController : Controller
	{
		[HttpGet]
		public async Task<IActionResult> Index([FromServices] DisciplineService disciplineService)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<List<DisciplineVO>> response = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

			return View("/Views/Coordinator/Disciplines/Index.cshtml", response);
		}

		[HttpGet("Add")]
		public IActionResult Add() => View("/Views/Coordinator/Disciplines/Add.cshtml");

		[HttpPost]
		public async Task<IActionResult> AddDiscipline([FromServices] DisciplineService disciplineService, ResultModel<DisciplineVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<DisciplineVO> response = await disciplineService.AddDisciplineTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Disciplines/Add.cshtml", new ResultModel<DisciplineVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplinesResponse = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

			if (disciplinesResponse.StatusCode == HttpStatusCode.OK)
			{
				disciplinesResponse.Message = response.Message;
				disciplinesResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Disciplines/Index.cshtml", disciplinesResponse);
		}

		[HttpGet("Update/{disciplineId}")]
		public async Task<IActionResult> Update([FromServices] DisciplineService disciplineService, [Required] Guid disciplineId)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<DisciplineVO> response = await disciplineService.GetDisciplineByDisciplineIdTaskAsync(disciplineId, token);

			return View("/Views/Coordinator/Disciplines/Update.cshtml", response);
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateDiscipline([FromServices] DisciplineService disciplineService, ResultModel<DisciplineVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<DisciplineVO> response = await disciplineService.UpdateDisciplineTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Disciplines/Update.cshtml", new ResultModel<DisciplineVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplinesResponse = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

			if (disciplinesResponse.StatusCode == HttpStatusCode.OK)
			{
				disciplinesResponse.Message = response.Message;
				disciplinesResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Disciplines/Index.cshtml", disciplinesResponse);
		}

		[HttpPost("Delete/{disciplineId}")]
		public async Task<IActionResult> Delete([FromServices] DisciplineService disciplineService, [Required] Guid disciplineId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<bool> response = await disciplineService.DeleteDisciplineTaskAsync(disciplineId, token);

				ResultModel<List<DisciplineVO>> disciplinesResponse = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);

				if (disciplinesResponse.StatusCode == HttpStatusCode.OK)
				{
					disciplinesResponse.StatusCode = response.StatusCode;
					disciplinesResponse.Message = response.Message;
				}

				return View("/Views/Coordinator/Disciplines/Index.cshtml", disciplinesResponse);
			}

			return BadRequest();
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Controllers/Coordinator/LessonsController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

using UniLinks.Client.Site.Services.Coordinator;
using UniLinks.Dependencies.Attributes;
using UniLinks.Dependencies.Data.VO;
using UniLinks.Dependencies.Data.VO.Lesson;
using UniLinks.Dependencies.Enums;
using UniLinks.Dependencies.Models;

namespace UniLinks.Client.Site.Controllers.Coordinator
{
	[Route("Coordinator/[Controller]")]
	[Authorizes(UserTypeEnum.Coordinator)]
	public class LessonsController : Controller
	{
		[HttpGet]
		public async Task<IActionResult> Index([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
			ResultModel<List<LessonDisciplineVO>> lessons = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

			return View("/Views/Coordinator/Lessons/Index.cshtml", lessons);
		}

		[HttpGet("Add")]
		public IActionResult Add() => View("/Views/Coordinator/Lessons/Add.cshtml");

		[HttpPost]
		public async Task<IActionResult> AddLesson([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService, ResultModel<LessonVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<LessonVO> response = await lessonService.AddLessonTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Lessons/Add.cshtml", new ResultModel<LessonVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
			ResultModel<List<LessonDisciplineVO>> lessonsResponse = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

			if (lessonsResponse.StatusCode == HttpStatusCode.OK)
			{
				lessonsResponse.Message = response.Message;
				lessonsResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Lessons/Index.cshtml", lessonsResponse);
		}

		[HttpGet("Update/{lessonId}")]
		public async Task<IActionResult> Update([FromServices] LessonService lessonService, [Required] Guid lessonId)
		{
			string token = User.FindFirst("Token").Value;

			ResultModel<LessonVO> response = await lessonService.GetLessonByIdTaskAsync(lessonId, token);

			return View("/Views/Coordinator/Lessons/Update.cshtml", response);
		}

		[HttpPost("Update")]
		public async Task<IActionResult> UpdateLesson([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService, ResultModel<LessonVO> request)
		{
			string token = User.FindFirst("Token").Value;

			request.Object.CourseId = Guid.Parse(User.FindFirst("CourseId").Value);

			ResultModel<LessonVO> response = await lessonService.UpdateLessonTaskAsync(request.Object, token);

			if (response.StatusCode != HttpStatusCode.Created)
				return View("/Views/Coordinator/Lessons/Update.cshtml", new ResultModel<LessonVO>
				{
					Object = request.Object,
					Message = response.Message,
					StatusCode = response.StatusCode
				});

			ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
			ResultModel<List<LessonDisciplineVO>> lessonsResponse = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

			if (lessonsResponse.StatusCode == HttpStatusCode.OK)
			{
				lessonsResponse.Message = response.Message;
				lessonsResponse.StatusCode = response.StatusCode;
			}

			return View("/Views/Coordinator/Lessons/Index.cshtml", lessonsResponse);
		}

		[HttpPost("Delete/{lessonId}")]
		public async Task<IActionResult> Delete([FromServices] LessonService lessonService, [FromServices] DisciplineService disciplineService, [Required] Guid lessonId)
		{
			if (ModelState.IsValid)
			{
				string token = User.FindFirst("Token").Value;

				ResultModel<bool> response = await lessonService.RemoveLessonTaskAsync(lessonId, token);

				ResultModel<List<DisciplineVO>> disciplines = await disciplineService.GetDisciplinesByCoordIdTaskAsync(token);
				ResultModel<List<LessonDisciplineVO>> lessons = await lessonService.GetAllLessonsByDisciplineIDsTaskAsync(token, disciplines.Object.Select(x => x.DisciplineId).ToList());

				if (disciplines.StatusCode == HttpStatusCode.OK && lessons.StatusCode == HttpStatusCode.OK)
				{
					lessons.StatusCode = response.StatusCode;
					lessons.Message = response.Message;
				}

				return View("/Views/Coordinator/Lessons/Index.cshtml", lessons);
			}

			return BadRequest();
		}
	}
}

Speckoz.UniLinks/UniLinks.Client.Site/Views/Coordinator/Classes/Add.cshtml
@inject UniLinks.Client.Site.Services.Coordinator.CourseService _courseService

@model ResultModel<ClassVO>

@{
    ViewData["Title"] = "Adicionar uma Sala";
}

@if (Model != null)
{
    switch (Model.StatusCode)
    {
        case System.Net.HttpStatusCode.Created:
        case System.Net.HttpStatusCode.OK:
            break;
        default:
            <script>
                sendMessage("@Model.Message", "error");
            </script>
            break;
    }
}

<div style="padding-top: 20px">
    <div class="text-center">
        <span>Informe os campos abaixo para prosseguir!</span>
    </div>
    <div style="padding: 10px">
        <form method="post" asp-controller="Classes" asp-action="AddClass">
            <div class="row">
                <div class="col-12">
                    <div class="form-group md-form">
                        <input type="text" id="classUri" class="form-control theme-text validate" asp-for="Object.URI" style="margin-bottom: 0" aria-describedby="classURIHelp" required />
                        <label for="classUri" data-error="wrong" data-success="right">Url da Sala</label>
                        <small id="classURIHelp" class="form-text text-muted">
                            Formato: https://us.bbcollab.com/guest/{ID}
                        </small>
                    </div>
                </div>
                <div class="col-6">
                    @{
                        string token = User.FindFirst("Token").Value;
                        var courseInfo = await _courseService.GetCourseByCoordIdTaskAsync(token);
                    }

                    <div class="form-group">
                        <label style="font-size: 14px; color: #757575;">Periodo</label>
                        <select asp-for="Object.Period" id="periodSelector">
                            @{
                                for (int i = 1; i <= courseInfo.Object.Periods; i++)
                                {
                                    <option value="@i">@(i)º Periodo</option>
                                }
                            }
                        </select>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label style="font-size: 14px; color: #757575;">Dias da semana</label>
                        <select id="weekDaysSelector" asp-for="Object.WeekDays" asp-items="Html.GetEnumSelectList<WeekDaysEnum>()">
                        </select>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center" style="margin-top: 35px">
                <button type="submit" class="btn btn-success waves-effect">Adicionar</button>
                <a class="btn btn-outline-grey waves-effect" asp-action="Index" asp-controller="Classes">Voltar</a>
            </div>
        </form>
    </div>
</div>

<script src="~/js/choices.js"></script>
<script>
    new Choices("#periodSelector");
    new Choices("#weekDaysSelector");
</script>

Speckoz.UniLinks/UniLinks.Client.Site/Views/Coordinator/Classes/Index.cshtml
@using EnumsNET
@using System.Net

@model ResultModel<List<ClassVO>>

@{
    ViewData["Title"] = "Salas";
}

@if (Model != null)
{
    switch (Model.StatusCode)
    {
        case HttpStatusCode.OK:
            break;
        case HttpStatusCode.Created:
        case HttpStatusCode.NoContent:
            <script>
                    sendMessage("@Model.Message", "success");
            </script>
            break;
        default:
            <script>
                    sendMessage("@Model.Message", "error");
            </script>
            break;
    }
}

<a asp-action="Add" asp-controller="Classes" class="btn btn-primary rounded-circle button-circle-bottom waves-effect p-2 px-3 waves-float animated bounceInRight add-button-circle">
    <i class="mdi mdi-plus mdi-24px"></i>
</a>

@if (Model.Object.Count() == 0)
{
    <p class="text-center p-4">Ops! Não existe nenhuma sala para mostrar! 😢</p>
}
else
{
    <div class="md-form md-outline form-lg animated bounceInDown" style="margin-left: 20px; margin-right: 20px">
        <input id="classesSearch" class="form-control form-control-lg" type="text" style="color: var(--theme-text); border-radius: 2em" />
        <label for="classesSearch">Pesquisar</label>

        <style>
            .md-form.md-outline label.active
            {
                background: var(--theme-bg);
                color: var(--theme-text);
            }
        </style>
    </div>

    <ul id="classesList" class="card-deck list-items animated bounceInUp" style="margin-left: 0; margin-right: 0">

        @foreach (ClassVO item in Model.Object)
        {
            <li class="card mb-4 theme-bg theme-text" style="max-width: 220px; min-width: 220px;  border-radius: 1.2em">
                <div>
                    <div style="position: relative">
                        <div style="height: 100%; left: 0; position: absolute; top: 0; width: 100%;border-radius: 1.2em 1.2em 0em 0em;background-image: url('img/classes.png'); background-size: cover; "></div>
                        <div style="display: flex; flex-direction: column; justify-content: space-between; height: 4.5rem; padding: 1rem 1rem 0.75rem; position: relative;">
                            <h6 style="font-weight: 600; color: white; width: auto; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; ">
                                @(item.WeekDays.AsString(EnumFormat.DisplayName))
                            </h6>
                            <p class="card-text" style="color: #c5c5c5; position: absolute; top: 40px;">
                                @(item.Period)º Período
                            </p>
                        </div>
                    </div>
                    <hr class="separator" style=" margin-top: 0; margin-bottom: 0;" />
                    <div style="padding: 15px">
                        <a target="_blank" href="@item.URI">Abrir Sala</a>
                    </div>
                    <hr class="separator" style=" margin-top: 0; margin-bottom: 0;" />
                    <div style="text-align: end; padding: 5px">
                        <div class="icons-td d-inline-flex">
                            <i class="mdi mdi-delete-outline mdi-24px red-text" onclick="confirmDelete('@item.WeekDays.AsString(EnumFormat.DisplayName)', '@item.Period', '@item.ClassId')" data-toggle="tooltip" data-placement="top" title="Remover" style="cursor: pointer"></i>
                        </div>
                        <form method="get" class="icons-td d-inline-flex" action="Coordinator/Classes/Update/@item.ClassId">
                            <button>
                                <i class="mdi mdi-monitor-edit mdi-24px blue-text" data-toggle="tooltip" data-placement="top" title="Editar"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </li>
        }
    </ul>
}

<div class="modal animated bounceInDown" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModal"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content theme-bg theme-text">
            <div class="modal-header border-0 text-center">
                <h4 class="modal-title w-100 font-weight-bold text-center ml-4">Confirmaçao</h4>
            </div>
            <div class="modal-body mx-3">
                <h6>
                    Realmente deseja excluir a sala de <span style="font-weight: 600" id="confirmDeleteModalWeekDays"></span> do <span style="font-weight: 600" id="confirmDeleteModalClassPeriod"></span><span style="font-weight: 600">º período</span> ?
                </h6>
            </div>

            <div class="modal-footer border-0 d-flex justify-content-center">
                <form method="post" class="icons-td d-inline-flex" id="confirmDeleteModalAction">
                    <button class="btn btn-outline-danger waves-effect" style="border: 0 !important;">Confirmar</button>
                </form>
                <button class="btn btn-danger waves-effect" data-dismiss="modal" aria-label="Close">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#classesSearch").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#classesList li").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    function confirmDelete(weekDays, classPeriod, classId) {
        document.getElementById("confirmDeleteModalWeekDays").innerText = weekDays;
        document.getElementById("confirmDeleteModalClassPeriod").innerText = classPeriod;
        document.getElementById("confirmDeleteModalAction").action = `/Coordinator/Classes/Delete/${classId}`;
        ShowModal("confirmDeleteModal");
    }
</script>